'use client';

import { useEffect, useState } from 'react';
import { Card } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Zap, AlertCircle, Lightbulb } from 'lucide-react';
import { mockCategories } from '@/lib/mock-data';
import { apiClient, AiSummaryResponse } from '@/lib/api';

export default function AIInsightsPage() {
  const [aiSummary, setAiSummary] = useState<AiSummaryResponse | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Keep budget alerts based on categories (local mock or real categories later)
  const overBudgetCategories = mockCategories.filter((cat) => (cat.spent || 0) > (cat.budget || 0));

  useEffect(() => {
    const fetchAi = async () => {
      try {
        setLoading(true);
        // Use current month/year as default
        const now = new Date();
        const month = now.getMonth() + 1;
        const year = now.getFullYear();

        const data = await apiClient.getAiSummary(month, year);
        setAiSummary(data);
        setError(null);
      } catch (err: any) {
        console.error('AI summary fetch failed', err?.response || err);
        setError(err.response?.data || err.message || 'Failed to fetch AI summary');
        // No hard fallback here; leave aiSummary null so UI can show message
      } finally {
        setLoading(false);
      }
    };

    fetchAi();
  }, []);

  return (
    <div className="flex flex-col h-full bg-background">
      {/* Header */}
      <div className="p-6 md:p-8 border-b border-border">
        <div className="flex items-center gap-3">
          <Zap size={32} className="text-accent" />
          <div>
            <h1 className="text-3xl md:text-4xl font-bold text-foreground">AI Insights</h1>
            <p className="text-muted-foreground mt-2">Smart recommendations based on your spending patterns</p>
          </div>
        </div>
      </div>

      {/* Content */}
      <div className="flex-1 overflow-auto p-6 md:p-8">
        <div className="max-w-4xl mx-auto space-y-6">
          {/* AI Summary Card */}
          <Card className="p-6">
            <div className="flex items-start gap-4 mb-4">
              <Lightbulb className="text-accent flex-shrink-0 mt-1" size={24} />
              <div className="flex-1">
                <h3 className="font-semibold text-foreground">AI Monthly Summary</h3>
                <p className="text-xs text-muted-foreground">Overview generated by the analytics AI</p>
              </div>
            </div>

            {loading ? (
              <div className="text-sm text-muted-foreground">Loading AI insights…</div>
            ) : error ? (
              <div className="space-y-2">
                <div className="text-sm text-destructive">Failed to load AI summary: {String(error)}</div>
                <div className="text-sm text-muted-foreground">You can try again later.</div>
              </div>
            ) : aiSummary ? (
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <p className="text-sm text-muted-foreground">Report for</p>
                    <h4 className="text-lg font-semibold">{aiSummary.month}/{aiSummary.year}</h4>
                  </div>
                  <Badge className="bg-blue-100 text-blue-800">Risk: {aiSummary.risk_level}</Badge>
                </div>

                <div className="p-4 rounded-lg bg-muted/50">
                  <p className="text-sm text-foreground">{aiSummary.summary}</p>
                </div>

                <div>
                  <p className="text-sm font-medium text-foreground mb-2">Recommendations</p>
                  <ul className="list-disc ml-5 space-y-1 text-sm text-muted-foreground">
                    {aiSummary.recommendations.map((rec, idx) => (
                      <li key={idx}>{rec}</li>
                    ))}
                  </ul>
                </div>

                <div className="p-3 rounded-lg bg-accent/5 inline-block">
                  <p className="text-sm text-muted-foreground">Potential Savings</p>
                  <p className="text-lg font-semibold">{aiSummary.potential_savings}</p>
                </div>
              </div>
            ) : (
              <div className="text-sm text-muted-foreground">No AI summary available.</div>
            )}
          </Card>

          {/* Budget Alerts (existing) */}
          {/* {overBudgetCategories.length > 0 && (
            <Card className="p-6 border-l-4 border-l-destructive bg-destructive/5">
              <div className="flex items-start gap-4">
                <AlertCircle className="text-destructive flex-shrink-0 mt-1" size={24} />
                <div className="flex-1">
                  <h3 className="font-semibold text-foreground mb-2">Budget Alerts</h3>
                  <div className="space-y-2">
                    {overBudgetCategories.map((category) => (
                      <p key={category.id} className="text-sm text-muted-foreground">
                        <span className="font-medium text-destructive">{category.name}</span> is over budget by{' '}
                        <span className="font-semibold text-destructive">
                          ${((category.spent || 0) - (category.budget || 0)).toLocaleString()}
                        </span>
                      </p>
                    ))}
                  </div>
                </div>
              </div>
            </Card>
          )} */}

        </div>
      </div>
    </div>
  );
}
